### PR TITLE
(feature) add module asynchronous config using factory/existing/class

### PR DESCRIPTION
**Pull request by ksivamuthu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Added the async configuration method to the module, so that the azure table storage options can be injected into the module using a provider or factory.

Issue Number: #36 

## What is the new behavior?

The new behavior is

```typescript
const storageConfigFactory = async () => {
  sasKey: process.env['AZURE_STORAGE_SAS_KEY'],
  accountName: process.env['AZURE_STORAGE_ACCOUNT'],
  containerName: 'nest-demo-container',
};

@Module({
  controllers: [AppController],
  providers: [AppService],
  imports: [
    AzureStorageModule.withConfigAsync({
      useFactory: storageConfigFactory,
    }),
  ],
})
export class AppModule {}
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kurpav** [comment]
Any plans to merge it?

**Comment by ksivamuthu** [comment]
@kamilmysliwiec @manekinekko Any plans on merging this?

**Comment by lukazlatecan** [comment]
Any news on this?

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
Thank you @ksivamuthu for sending this PR.

**Comment by bgolyoo** [comment]
When will this be released to npm? The latest version which is 2.1.1 doesn't have this feature.

**Comment by stijnswaanen** [comment]
yes, can this please be released to npm asap? Thx

**Comment by f5hajnal** [comment]
I was able to properly incorporate this to my project as a "helper" module. It works like a charm. However it would be amazing to see this be actually shipped to the latest npm version of the package... More than 6 months now since it's approval.
Thanks!

**Pull request merged**
